### ISSUE TITLE
make parser multilingual

### ISSUE THREAD

**Issue by inos-github** [strangetom/ingredient-parser#1]
is there any chance to make the parser multilingual? And what would be the best approach to achieve this?

**Comment by strangetom** [comment]
Hi @inos-github 

I think it is possible, but I don't have any plans to do it.

The main thing you would need is training data: a large number of  varied ingredient sentences in the language you want that all have the quantity, unit, name and comment labelled consistently. If you use a similar csv format to [nyt-ingredients-snapshot-2015.csv](https://github.com/strangetom/ingredient-parser/blob/master/train/data/nytimes/nyt-ingredients-snapshot-2015.csv) then you should be able to reuse a lot of the code in this repository. Gathering and labelled the training data is likely to be time consuming.

There are a few other things you would need to consider if you want to reuse the code here, because some parts of the pre-processing the ingredient sentences go through are specific to English:

- Most of the contents of [_constants.py](https://github.com/strangetom/ingredient-parser/blob/master/ingredient_parser/_constants.py) are English, so you would need the equivalents in other languages
- Some of the features for each token of a sentence use English specific methods to calculate them. The stem and part of speech in [preprocess.py](https://github.com/strangetom/ingredient-parser/blob/9e8ca6481d8f59b455a6a394521fef62a0f46290/ingredient_parser/preprocess.py#L667) are both determined in English specific ways.

If you wanted to train a single model that could handle multiple languages, that might be a bit tricky. I think the simplest way would be to detect the language (also make that one of the labels in the training data), then have language-specific pre-processing to clean the input sentences and extract the features. Then train a single model on all the inputs and their features. To use the model, you would need to do the same language-specific pre-processing.

**Comment by inos-github** [comment]
Hallo @strangetom,
thanks for your detailed explanation! I will try to train a model for the German language but it will be the very first time for me, doing things like this so let's see ;)
