### ISSUE TITLE
"large" is not a unit

### ISSUE THREAD

**Issue by boxydog** [strangetom/ingredient-parser#12]
Case: "2 large shallots (about 4 ounces)" shows 'large' as a unit.

I tested on the latest "develop" branch.

<img width="785" alt="image" src="https://github.com/strangetom/ingredient-parser/assets/93335439/235dc640-0e51-4053-997d-b731389bc2dd">

**Comment by boxydog** [comment]
Oof. That seems wrong to me.

To me, a unit is an ingredient-independent word that I can get weight or volume from. "large canteloupe" and "large lime" are completely different, with the same "unit" of "large".

I suppose I can write some wrapper code to hack around this, and intercept things like small, medium, and large.

**Comment by boxydog** [comment]
In fact, I guess I've already had to deal with the "unit" of can/cans, which has the same problem.

You can close this if you wish.

**Comment by strangetom** [comment]
How would you prefer to handle words that represent an amount, like `large` or `can` or `wedge`?

**Comment by boxydog** [comment]
Great question. I haven't figured it out myself.

I feel these words are ingredient-dependent. "Large lime" and "Large watermelon" are different. "Lime wedge" and "Watermelon wedge" are different. So, it seems like a new thing, an ingredient size (or quantity) modifier.

In my own project (not nearly as polished as yours), I have a file where I keep the weight of some food items not typically measured in (ingredient-independent) units. So, a "lime" (no other units) is 120 grams. Why? I dunno, it's close enough, better than nothing. (Awhile back, I measured a few limes and took an average, I think.) So I imagine I can use the units of "large", "medium", etc. as modifiers on the "raw" food weight if it exists.

I don't know how your project should react to this. Maybe not at all. Before I have a concrete suggestion, I'd want to use it more concretely. I'm not devoting enough time to my project to firm up a proposal at the moment.

**Comment by strangetom** [comment]
I see what you're saying, and it's definitely food for thought. This conversation has given me a couple of ideas for potential future development:

- Introduce a `MOD` or `SIZE` label to the model. This wouldn't be very difficult, just a bit tedious to update the labels training data. There is some further thinking to be done about how it is presented in the `ParsedIngredient` object and also how would work when it is modifying the size of the unit, not the ingredient (e.g. 1 large pinch of salt)
- There might also be an opportunity to make use of [pint](https://pint.readthedocs.io/en/stable/) for units that are independent of the ingredient instead of just returning everything as a string.

**Comment by boxydog** [comment]
Sounds interesting.

Just to summarize, I think one concrete goal for units should be to end up in grams (weight). That can perhaps help guide such thoughts.

Note: in the U.S., we use volume for a lot of ingredients, but at least the baking world has figured out that weight is better. If you search, you'll see people recommend a food scale.

**Comment by strangetom** [comment]
The latest release adds a new `size` field to `ParsedIngredient`  which is for words that describe the size of the ingredient, like large or small. An interesting side effect of this change is a notable increase in model performance.

This release also uses [pint](https://pint.readthedocs.io/) to represent units instead of using a string (where possible). This means that it's now easier to convert to your preferred units.

Closing this as complete.

**Comment by boxydog** [comment]
Sounds amazing, I'll have to check it out.
