### ISSUE TITLE
Add pre-commit filters with ruff

### ISSUE THREAD

**Issue by boxydog** [strangetom/ingredient-parser#8]
Lots of python codebases are now using [ruff](https://github.com/astral-sh/ruff) to standardize and check their codebase, and [pre-commit](https://pre-commit.com/) to run those checks before each git commit.

**Comment by strangetom** [comment]
Sounds like a good idea. I've already been using ruff for linting and black for formatting, but I've got no objection to using ruff for formatting as well.

To make this happen, I think the following would be needed:

- Update requirements-dev.txt
  - Remove black
  - Add pre-commit
  - Maybe set a minimum version for ruff that has the formatter?
- Configure pre-commit hooks for linting and formatting
- Update pyproject.toml to configure the ruff formatter the same way black is configured at the moment
- Update the development section of the README

You're welcome to open another PR, otherwise I'll take a look at doing this in a few days.
